In [2]:
import torch
import numpy as np

## Tensor Initialization

In [10]:
# From lists/ directly from data
data = [[1,2,3],[4,5,6]]
x_data = torch.tensor(data)
print(x_data)

# From numpy arrays
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

#From another tensor
x_ones = torch.ones_like(x_np) #retains properties of x_np
x_rand = torch.rand_like(x_np, dtype=torch.float) # Overrides properties of x_np
print(x_ones)
print(x_rand)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0.7272, 0.5052, 0.4270],
        [0.0467, 0.5149, 0.2899]])


##### You can directly from a shape as well

In [11]:
shape = (2,3) # Tuple indicating the shape

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)

print(rand_tensor)
print(ones_tensor)

tensor([[0.5108, 0.0362, 0.0179],
        [0.0066, 0.8072, 0.0039]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# Tensor Attributes

In [12]:
shape = (4,5)
tensor = torch.rand(shape)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([4, 5])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Moving Tensor to the GPU

In [18]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

print(tensor.device)

False
cpu


# Tensor Operations